### ISSUE TITLE
Properly arrange the Contributors names

### ISSUE THREAD

**Issue by Naman-sharma00100** [Naman-sharma00100/Introduction-webpage#26]
Properly arrange the  names of people who have contributed so far, separating the ones into categories for these year and the previous years commits.

**Comment by dhrumishah** [comment]
Hey @Naman-sharma00100, I would like to improve this. Can you assign me?

**Comment by Naman-sharma00100** [comment]
Yaa sure.

**Comment by dhrumishah** [comment]
> Yaa sure.

I have made PR. And changed somewhat UI.
