### ISSUE TITLE
Email Click is throwing 404 error page

### ISSUE THREAD

**Issue by Abhishek765** [Naman-sharma00100/Introduction-webpage#37]
hey @Naman-sharma00100  the Email Id link is broken let me fix that, please assign this to me

![image](https://user-images.githubusercontent.com/43133456/193793705-82d4f6a7-8446-4050-bdd5-c22021fc727c.png)
![image](https://user-images.githubusercontent.com/43133456/193793737-7ac1b30b-ee38-42b2-8a31-64af8021a716.png)

**Comment by darshitdudhaiya** [comment]
this issue is solved

**Comment by Abhishek765** [comment]
Resolved here: #39
