### ISSUE TITLE
[FEATURE] Add a customized color on selection and animation on scroll feature

### ISSUE THREAD

**Issue by mohammadshaad** [Naman-sharma00100/Introduction-webpage#51]
I want to add a customized color on selection and animation on scroll feature on the website which will make the website look more cool. Kindly assign me this issue.

**Comment by rajatrai30** [comment]
Hello Sir,
I would like to contribute for this issue.
please assign me with this task

**Comment by mohammadshaad** [comment]
@rajatrai30 I made this issue and it will be assigned to me only. You should make your own issue to contribute, you don't know open-source contribution manners and rules?
